version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgresql_db
    environment:
      - POSTGRES_USER=pedrooyarzun
      - POSTGRES_PASSWORD=Pedro123.
      - POSTGRES_DB=todo-app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: